version: '2'
services:
  solution-selection:
    image: miwurster/pbdmg-solution-selection
    ports:
      - '4200:8080'
    networks:
      - opentosca
  winery:
    image: miwurster/pbdmg-winery
    ports:
      - '8080:8080'
    environment:
      - WINERY_REPOSITORY_URL=https://github.com/miwurster/solution-selection-repository.git
    networks:
      - opentosca
networks:
  opentosca:
    driver: bridge
